# Generated by Django 2.2.3 on 2019-11-05 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ic_marathon_app.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=200)),
                ('user_goal', models.BooleanField(default=False)),
                ('cec', models.CharField(blank=True, max_length=30)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('category', models.CharField(blank=True, choices=[(None, 'Please select a category'), ('Runner', 'Baby Runner'), ('Runner', 'Runner'), ('Biker', 'Biker')], max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('photo_evidence', models.ImageField(upload_to='', validators=[ic_marathon_app.validators.validate_file_size])),
                ('time', models.IntegerField(help_text='Workout in minutes', validators=[ic_marathon_app.validators.validate_workout_time])),
                ('belongs_to', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.Profile')),
            ],
        ),
    ]
