# Generated by Django 2.2.3 on 2019-09-02 21:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('distance', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('photo_evidence', models.ImageField(upload_to='')),
            ],
        ),
    ]
