# Generated by Django 2.2.3 on 2019-11-15 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_goal', models.BooleanField(default=False)),
                ('avatar', models.CharField(max_length=200)),
                ('cec', models.CharField(blank=True, max_length=30)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('category', models.CharField(choices=[('beginnerrunner', 'Beginner Runner'), ('runner', 'Runner'), ('biker', 'Biker')], default='beginnerrunner', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('photo_evidence', models.ImageField(upload_to='')),
                ('time', models.IntegerField(help_text='Workout in minutes')),
                ('belongs_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.Profile')),
            ],
        ),
    ]
