# Generated by Django 2.2.3 on 2019-12-02 18:50

from django.db import migrations, models
import ic_marathon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('beginnerrunner', 'Beginner Runner'), ('runner', 'Runner'), ('biker', 'Biker')], default='beginnerrunner', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workout',
            name='photo_evidence',
            field=models.ImageField(upload_to='', validators=[ic_marathon_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.TimeField(default='00:00', help_text='Workout in minutes', validators=[ic_marathon_app.validators.validate_workout_time]),
        ),
    ]
