# Generated by Django 2.2.3 on 2019-11-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('babyrunner', 'Baby Runner'), ('runner', 'Runner'), ('biker', 'Biker')], default='babyrunner', max_length=10),
            preserve_default=False,
        ),
    ]
