# Generated by Django 2.2.3 on 2019-11-16 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0002_auto_20191116_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='belongs_to',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.Profile'),
        ),
    ]
