# Generated by Django 2.2.3 on 2019-12-03 23:53

from django.db import migrations, models
import ic_marathon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0002_auto_20191202_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='photo_evidence',
            field=models.ImageField(upload_to='', validators=[ic_marathon_app.validators.validate_file_size], verbose_name='Evidence'),
        ),
    ]
