# Generated by Django 2.2.3 on 2019-09-02 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ic_marathon_app', '0002_auto_20190902_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='belongs_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
