# Generated by Django 2.2.3 on 2019-09-02 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ic_marathon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ic_marathon_app', '0003_workout_belongs_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='workout',
            name='photo_evidence',
            field=models.ImageField(upload_to='', validators=[ic_marathon_app.validators.validate_file_size]),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cec', models.CharField(max_length=30)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('category', models.CharField(choices=[(None, 'Please select a category'), ('Runner', 'Runner'), ('Biker', 'Biker')], max_length=10)),
                ('team', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='ic_marathon_app.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
