# Generated by Django 2.2.3 on 2019-12-09 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0003_auto_20191203_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 16, 5, 27, 144722)),
            preserve_default=False,
        ),
    ]
