# Generated by Django 2.2.3 on 2019-09-02 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0004_auto_20190902_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='belongs_to',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.Profile'),
        ),
    ]
