# Generated by Django 2.2.3 on 2019-11-16 23:52

from django.db import migrations, models
import ic_marathon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0004_auto_20191116_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='photo_evidence',
            field=models.ImageField(upload_to='', validators=[ic_marathon_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.TimeField(help_text='Workout in minutes', validators=[ic_marathon_app.validators.validate_workout_time]),
        ),
    ]
