# Generated by Django 2.2.3 on 2019-11-17 00:54

from django.db import migrations, models
import ic_marathon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0005_auto_20191116_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.TimeField(default='00:00', help_text='Workout in minutes', validators=[ic_marathon_app.validators.validate_workout_time]),
        ),
    ]
