# Generated by Django 2.2.3 on 2019-12-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0005_auto_20191209_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='KM'),
        ),
    ]
