# Generated by Django 2.2.3 on 2019-11-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0006_auto_20191117_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
