# Generated by Django 2.2.3 on 2019-09-02 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0006_auto_20190902_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(blank=True, choices=[(None, 'Please select a category'), ('Runner', 'Runner'), ('Biker', 'Biker')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cec',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_team', to='ic_marathon_app.Team'),
        ),
    ]
