# Generated by Django 2.2.3 on 2019-12-11 19:31

from django.db import migrations, models
import ic_marathon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0006_auto_20191210_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[ic_marathon_app.validators.validate_distance], verbose_name='KM'),
        ),
    ]
