# Generated by Django 2.2.3 on 2019-12-12 01:10

from django.db import migrations, models
import ic_marathon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0007_auto_20191211_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date_time',
            field=models.DateTimeField(validators=[ic_marathon_app.validators.validate_date], verbose_name='Date'),
        ),
    ]
