# Generated by Django 2.2.3 on 2019-09-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0009_auto_20190902_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_distance',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_goal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='team_goal',
            field=models.BooleanField(default=False),
        ),
    ]
