# Generated by Django 2.2.13 on 2020-11-01 13:45

from django.db import migrations, models
import ic_marathon_app.validators
import ic_marathon_site.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0009_auto_20191219_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='photo_evidence',
            field=models.ImageField(storage=ic_marathon_site.storage_backends.PrivateMediaStorage(), upload_to='', validators=[ic_marathon_app.validators.validate_file_size], verbose_name='Evidence'),
        ),
    ]
