# Generated by Django 2.2.3 on 2019-09-18 22:33

import datetime
from django.db import migrations, models
import ic_marathon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0010_auto_20190905_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='time',
            field=models.DurationField(default=datetime.timedelta(seconds=900), validators=[ic_marathon_app.validators.validate_workout_time]),
            preserve_default=False,
        ),
    ]
