# Generated by Django 2.2.3 on 2019-11-04 03:32

from django.db import migrations, models
import django.db.models.deletion
import ic_marathon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0012_auto_20190918_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_team', to='ic_marathon_app.Team', validators=[ic_marathon_app.validators.validate_team_members]),
        ),
    ]
